services:
  - type: web
    name: vurohith-books
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: My Files
      - key: FLASK_SECRET_KEY
        sync: false
